#!/bin/bash
# SwarmIA Simple Installer - Works with curl | sudo bash

set -e

# Colores
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m' # No Color

# Configuración
SWARMIA_DIR="/opt/swarmia"
CONFIG_DIR="/etc/swarmia"
LOGS_DIR="/var/log/swarmia"
DATA_DIR="/var/lib/swarmia"
PORT="3000"
REPO_URL="https://github.com/nicky686-22/test.git"

# Banner
echo -e "${GREEN}"
echo "╔══════════════════════════════════════════════════════════════╗"
echo "║                 SwarmIA Simple Installer                     ║"
echo "║                    Automatic Installation                    ║"
echo "╚══════════════════════════════════════════════════════════════╝"
echo -e "${NC}"

# Verificar root
if [[ $EUID -ne 0 ]]; then
    echo -e "${RED}[!] This installer must be run as root${NC}"
    exit 1
fi

# Detectar sistema
echo -e "${BLUE}[*] Detecting system...${NC}"
if [ -f /etc/os-release ]; then
    . /etc/os-release
    OS=$NAME
    VER=$VERSION_ID
else
    OS=$(uname -s)
    VER=$(uname -r)
fi
echo -e "${GREEN}[✓] System: $OS $VER${NC}"

# Verificar si ya está instalado
if [ -d "$SWARMIA_DIR" ]; then
    echo -e "${YELLOW}[!] SwarmIA is already installed, updating...${NC}"
    ACTION="update"
else
    echo -e "${BLUE}[*] Installing SwarmIA fresh...${NC}"
    ACTION="install"
fi

# Instalar dependencias
echo -e "${BLUE}[*] Installing dependencies...${NC}"
apt-get update > /dev/null 2>&1
apt-get install -y python3 python3-pip python3-venv git curl wget net-tools > /dev/null 2>&1
echo -e "${GREEN}[✓] Dependencies installed${NC}"

# Crear directorios
echo -e "${BLUE}[*] Creating directories...${NC}"
mkdir -p "$SWARMIA_DIR" "$CONFIG_DIR" "$LOGS_DIR" "$DATA_DIR" "$DATA_DIR/uploads" "$DATA_DIR/models"
echo -e "${GREEN}[✓] Directories created${NC}"

# Descargar SwarmIA
echo -e "${BLUE}[*] Downloading SwarmIA from GitHub...${NC}"
cd "$SWARMIA_DIR"

# Limpiar directorio si existe
rm -rf "$SWARMIA_DIR"/* 2>/dev/null || true

# Clonar repositorio con timeout
timeout 30 git clone "$REPO_URL" . 2>/dev/null
if [ $? -eq 0 ]; then
    echo -e "${GREEN}[✓] Repository cloned successfully${NC}"
else
    echo -e "${RED}[!] Git clone failed or timed out${NC}"
    echo -e "${YELLOW}[*] Trying alternative method...${NC}"
    # Intentar con wget
    cd /tmp
    wget -q "$REPO_URL/archive/main.zip" -O swarmia.zip 2>/dev/null && unzip -q swarmia.zip -d "$SWARMIA_DIR" && mv "$SWARMIA_DIR/test-main"/* "$SWARMIA_DIR/" && rm -rf "$SWARMIA_DIR/test-main" swarmia.zip
    echo -e "${GREEN}[✓] Downloaded via wget${NC}"
fi

# Instalar dependencias Python
echo -e "${BLUE}[*] Installing Python dependencies...${NC}"
cd "$SWARMIA_DIR"
if [ -f "requirements.txt" ]; then
    # Para Ubuntu 24.04 que tiene externally-managed-environment
    pip3 install --break-system-packages -r requirements.txt > /dev/null 2>&1
    echo -e "${GREEN}[✓] Python dependencies installed${NC}"
else
    echo -e "${YELLOW}[!] No requirements.txt found${NC}"
    # Instalar dependencias básicas
    pip3 install --break-system-packages flask flask-cors requests > /dev/null 2>&1
    echo -e "${GREEN}[✓] Basic Python dependencies installed${NC}"
fi

# Crear archivo de configuración
echo -e "${BLUE}[*] Creating configuration file...${NC}"
cat > "$CONFIG_DIR/config.yaml" << CONFIG_EOF
# SwarmIA Configuration
# Generated by installer on $(date)

# Server settings
server:
  host: "0.0.0.0"
  port: $PORT
  debug: false

# AI Backend configuration
ai:
  backend: "deepseek"
  
  deepseek:
    api_key: ""
    model: "deepseek-chat"
    base_url: "https://api.deepseek.com"
  
  llama:
    model_path: ""
    n_ctx: 2048
    n_gpu_layers: -1

# Messaging platforms
messaging:
  platform: "none"
  
  whatsapp:
    phone_number: ""
    session_path: "$DATA_DIR/whatsapp_session"
  
  telegram:
    bot_token: ""
    admin_ids: []

# Database
database:
  path: "$DATA_DIR/swarmia.db"
  type: "sqlite"

# Logging
logging:
  level: "INFO"
  file: "$LOGS_DIR/swarmia.log"
  max_size_mb: 10
  backup_count: 5

# Security
security:
  api_key_enabled: false
  cors_origins: ["*"]
CONFIG_EOF
echo -e "${GREEN}[✓] Configuration file created${NC}"

# Crear servicio systemd
echo -e "${BLUE}[*] Creating systemd service...${NC}"
cat > /etc/systemd/system/swarmia.service << SERVICE_EOF
[Unit]
Description=SwarmIA AI System
After=network.target

[Service]
Type=simple
User=root
WorkingDirectory=$SWARMIA_DIR
Environment="PYTHONPATH=$SWARMIA_DIR"
Environment="SWARMIA_CONFIG=$CONFIG_DIR/config.yaml"
ExecStart=/usr/bin/python3 $SWARMIA_DIR/src/core/main.py
Restart=on-failure
RestartSec=5
StandardOutput=append:$LOGS_DIR/swarmia.log
StandardError=append:$LOGS_DIR/swarmia-error.log

[Install]
WantedBy=multi-user.target
SERVICE_EOF

systemctl daemon-reload
echo -e "${GREEN}[✓] Systemd service created${NC}"

# Iniciar servicio
echo -e "${BLUE}[*] Starting SwarmIA service...${NC}"
systemctl enable swarmia > /dev/null 2>&1
systemctl restart swarmia

sleep 3

if systemctl is-active --quiet swarmia; then
    echo -e "${GREEN}[✓] SwarmIA service is running${NC}"
else
    echo -e "${RED}[!] Failed to start service${NC}"
    echo -e "${YELLOW}[*] Checking if main.py exists...${NC}"
    if [ -f "$SWARMIA_DIR/src/core/main.py" ]; then
        echo -e "${GREEN}[✓] main.py found, trying manual start...${NC}"
        cd "$SWARMIA_DIR"
        python3 src/core/main.py &
        sleep 2
        if ps aux | grep -v grep | grep -q "python3.*main.py"; then
            echo -e "${GREEN}[✓] SwarmIA started manually${NC}"
        else
            echo -e "${RED}[!] Manual start also failed${NC}"
        fi
    else
        echo -e "${RED}[!] main.py not found at $SWARMIA_DIR/src/core/main.py${NC}"
    fi
fi

# Mensaje de finalización
local ip_address=$(hostname -I | awk '{print $1}')
echo ""
echo -e "${GREEN}✅ SwarmIA has been successfully installed!${NC}"
echo ""
echo -e "${CYAN}Access Information:${NC}"
echo -e "  Dashboard:    http://$ip_address:$PORT"
echo -e "  Health check: http://$ip_address:$PORT/health"
echo ""
echo -e "${CYAN}Service Management:${NC}"
echo -e "  Check status: systemctl status swarmia"
echo -e "  View logs:    journalctl -u swarmia -f"
echo ""
echo -e "${GREEN}══════════════════════════════════════════════════════════════${NC}"
